export { Archive, CardImage, InfoCircle, Eye, EyeSlash, Code, CodeSlash, Trash } from 'styled-icons/bootstrap';
export { Page, Handshake } from 'styled-icons/fluentui-system-filled';
export { DocumentOnePage,  } from 'styled-icons/fluentui-system-regular';
export { Layout, Edit, User } from 'styled-icons/boxicons-regular';
export { QuoteAltLeft, QuoteAltRight } from 'styled-icons/boxicons-solid';
export { Preview } from 'styled-icons/material';
export { Dashboard, DashboardCustomize } from 'styled-icons/material-rounded';
export { LockPassword } from 'styled-icons/remix-fill';
export { Email, OldPhone, Location } from 'styled-icons/entypo';
export { Law } from 'styled-icons/octicons';
export { HandsHelping } from 'styled-icons/fa-solid';
export { Rocket } from 'styled-icons/ionicons-outline';